<?php

namespace Modules\Suite\Repositories;

use Modules\Suite\Entities\SuiteType;
use Prettus\Repository\Eloquent\BaseRepository;

class SuiteTypeRepository extends BaseRepository
{
    public function model() {
        return SuiteType::class;
    }

    public function find($id, $column = ['*']) {
        return parent::find($id, $column);
    }

    public function create(array $attributes)
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}