<?php

namespace Modules\Voyage\Repositories;

use Modules\Voyage\Entities\VoyageExperience;
use Prettus\Repository\Eloquent\BaseRepository;

class VoyageExperienceRepository extends BaseRepository
{
    public function model() {
        return VoyageExperience::class;
    }

    public function find($id, $column = ['*']) {
        return parent::find($id, $column);
    }

    public function create(array $attributes)
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}